### ISSUE TITLE
jdk11 & arm64 throws NullPointerException in StateSetEnumerator.reset(..)

### ISSUE THREAD

**Issue by michaelsembwever** [jflex-de/jflex#910]
In the Apache Cassandra CI builds, occasionally we see the following exception, despite the jflex input not having changed:
```
 java.lang.NullPointerException
 	at jflex.StateSetEnumerator.reset(StateSetEnumerator.java:40)
 	at jflex.NFA.containsFinal(NFA.java:295)
 	at jflex.NFA.getDFA(NFA.java:539)
 	at jflex.Main.generate(Main.java:80)
 	at jflex.anttask.JFlexTask.execute(JFlexTask.java:65)
 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
 	at org.apache.tools.ant.Task.perform(Task.java:350)
 	at org.apache.tools.ant.Target.execute(Target.java:449)
 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1388)
 	at org.apache.tools.ant.Project.executeTarget(Project.java:1361)
 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
 	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
 	at org.apache.tools.ant.Main.runBuild(Main.java:834)
 	at org.apache.tools.ant.Main.startAnt(Main.java:223)
 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
```

We use 1.6.0

The jflex file is here: https://github.com/apache/cassandra/blob/trunk/src/java/org/apache/cassandra/index/sasi/analyzer/StandardTokenizerImpl.jflex

We build it with `ant` here: https://github.com/apache/cassandra/blob/trunk/build.xml#L433-L440

Example CI failure is here: https://ci-cassandra.apache.org/view/Cassandra%204.0/job/Cassandra-trunk-artifacts/501/jdk=jdk_11_latest,label=cassandra-arm64/console
<img width="500" alt="Screenshot 2021-04-07 at 21 53 06" src="https://user-images.githubusercontent.com/559444/113925718-a4a02700-97eb-11eb-9b07-63bc7dab395b.png">

So far it has happened only on the JDK 11 arm64 builds.

downstream: https://issues.apache.org/jira/browse/CASSANDRA-16576

**Comment by regisd** [comment]
1.6.0 was released in 2014. Please try with a more recent version.

**Comment by regisd** [comment]
From the stacktrace, it seems `numDFA` is `null` in `NFA.getDFA()`
https://github.com/jflex-de/jflex/blob/v1.6.0/jflex/src/main/java/jflex/NFA.java#L539

**Comment by regisd** [comment]
I'll leave the issue open because the code was moved  in https://github.com/jflex-de/jflex/blob/master/jflex/src/main/java/jflex/dfa/DfaFactory.java but I don't think it has radically changed.

**Comment by michaelsembwever** [comment]
An upgrade to jflex 1.8.2 appears to have fixed the issue.

In trunk it was failing ~20-30% of the time.

This [patch](https://github.com/apache/cassandra/compare/trunk...thelastpickle:mck/16576/trunk) was run 30 times in a loop without any failure here: [!https://ci-cassandra.apache.org/job/Cassandra-devbranch-artifacts/jdk=jdk_11_latest,label=cassandra-arm64/590//badge/icon!](https://ci-cassandra.apache.org/job/Cassandra-devbranch-artifacts/jdk=jdk_11_latest,label=cassandra-arm64/590/)

It is no guarantee, but looks good enough to close.
