### ISSUE TITLE
Unexpected dump?

### ISSUE THREAD

**Issue by billfenlason** [jflex-de/jflex#972]
I'm using a java processbuilder with a jflex jar file.  When I use an old jar (1.4.1) all works as expected, but when I use the latest version (1.8.2) I get this dump. 
Exception in thread "main" java.lang.NoClassDefFoundError: java_cup/runtime/Scanner
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at jflex.generator.LexGenerator.generate(LexGenerator.java:70)
	at jflex.Main.generate(Main.java:320)
	at jflex.Main.main(Main.java:336)
Caused by: java.lang.ClassNotFoundException: java_cup.runtime.Scanner
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 12 more

What have I done wrong?  Thanks.

**Comment by billfenlason** [comment]
Sorry for the interruption - never mind.

I now see that the java_cup package was left out of the build.  

Have you considered providing a downloadable jar file?  That would solve the problem.

Again - please mark this as resolved.

**Comment by lsf37** [comment]
No worries, but the jar file in the distribution should actually contain those classes:

```
~/jflex-1.8.2/lib $ jar -t -f jflex-full-1.8.2.jar
META-INF/
META-INF/MANIFEST.MF
...
java_cup/
java_cup/runtime/
java_cup/runtime/XMLElement$NonTerminal.class
java_cup/runtime/SymbolFactory.class
java_cup/runtime/SyntaxTreeTransform$ChainRemover.class
java_cup/runtime/DefaultSymbolFactory.class
java_cup/runtime/SyntaxTreeDFS.class
java_cup/runtime/ComplexSymbolFactory$Location.class
java_cup/runtime/XMLElement$Error.class
java_cup/runtime/SyntaxTreeDFS$Visitor.class
java_cup/runtime/SyntaxTreeTransform$1.class
java_cup/runtime/Scanner.class
java_cup/runtime/ScannerBuffer.class
java_cup/runtime/lr_parser.class
java_cup/runtime/SyntaxTreeDFS$AbstractVisitor.class
java_cup/runtime/Symbol.class
java_cup/runtime/SyntaxTreeDFS$ElementHandler.class
java_cup/runtime/ComplexSymbolFactory$ComplexSymbol.class
java_cup/runtime/SyntaxTreeTransform.class
java_cup/runtime/SyntaxTreeXPath.class
java_cup/runtime/ComplexSymbolFactory.class
java_cup/runtime/virtual_parse_stack.class
java_cup/runtime/XMLElement.class
java_cup/runtime/XMLElement$Terminal.class
META-INF/maven/com.github.vbmacher/
META-INF/maven/com.github.vbmacher/java-cup-runtime/
META-INF/maven/com.github.vbmacher/java-cup-runtime/pom.xml
META-INF/maven/com.github.vbmacher/java-cup-runtime/pom.properties
```

(This is from the `lib/jflex-full-1.8.2.jar` in `jflex-1.8.2.tar.gz` file of the release)

**Comment by lsf37** [comment]
If you're building from source, you might be missing the step where the full jar is produced from the JFlex jar and the java_cup runtime classes.

**Comment by billfenlason** [comment]
Hello Gerwin,

Actually I'm writing a JFlex editor for Eclipse.  I'm working on the
builder, and have everything work for the JFlex jars for versions 1.4.1 and
1.6.1.  I've tried copying the java_cup files to the 1.8.2 jar, but I now
get another error message.

Here is the dump

Exception in thread "main" java.lang.NoSuchMethodError:
'java_cup.runtime.Symbol
 java_cup.runtime.SymbolFactory.newSymbol(java.lang.String, int,
java_cup.runtime.Symbol, java.lang.Object)'
at
jflex.core.LexParse$CUP$LexParse$actions.CUP$LexParse$do_action_part00000000(LexParse.java:1087)
at
jflex.core.LexParse$CUP$LexParse$actions.CUP$LexParse$do_action(LexParse.java:2257)
at jflex.core.LexParse.do_action(LexParse.java:598)
at java_cup.runtime.lr_parser.parse(lr_parser.java:584)
at jflex.generator.LexGenerator.generate(LexGenerator.java:74)
at jflex.Main.generate(Main.java:320)
at jflex.Main.main(Main.java:336)

I'm not sure what is going on, but I suspect somebody missed something with
a change since the 1.6.1 timeframe.

I hope your new business is going well!

Bill Fenlason

**Comment by billfenlason** [comment]
It took a bit of searching the web, but it turns out that the right jar is "jflex-full-1.8.2.jar".

**Comment by lsf37** [comment]
> It took a bit of searching the web, but it turns out that the right jar is "jflex-full-1.8.2.jar".

It is. Which one were you using? I'm asking because the JFlex release should really only contain that one, not the partial jars from which it is built, so if I overlooked one somewhere, that should probably be fixed.

**Comment by billfenlason** [comment]
I'm not sure what is going on - I found the file on the Australian site,
but now it is blocked.  I could find no -full jar at all on the jflex.de
site.  At one point the file showed on the git download link, but that is
gone now.  Anyway, I do wish you would include the jar file somewhere on
the git site - the third party / java_cup folder is empty, so there doesn't
seem to be any link or -full file.  I have the file and it is working, but
I can't re-create the process I used to get it.

**Comment by lsf37** [comment]
The download zip files linked from the web site and from the GitHub releases (e.g. https://github.com/jflex-de/jflex/releases/tag/v1.9.1) all contain do that jar file. It's the result of building the source, it does not make sense to include it in the source repository.
