### ISSUE TITLE
Unexpected exception encountered in JFlex

### ISSUE THREAD

**Issue by JefMihael** [jflex-de/jflex#974]
[scanner.flex](https://github.com/jflex-de/jflex/files/9978972/scanner.flex.txt)

[error.txt](https://github.com/jflex-de/jflex/files/9978978/error.txt)

i had a problem trying to generate a lexer with this .flex.
jflex version: jflex-1.8.2

**Comment by lsf37** [comment]
Thanks for reporting this, definitely looks like a bug. For discussion later, I've pasted the files inline here:

```jflex
package sintatico;


import sintatico.sym;
//import static lexico.Tokens.*;
%%

//%public
%cup
%full
%line
%char
%ignorecase 
%eofval{
    return new Symbol(sym.EOF, new String("Fim do Arquivo"));
%eofval}
//%class AnalisadorLexico
//%type Tokens   
BRANCO = [ \n\t\r]
/*%{
public String lexema;
/*public int ContaToken;*/
%}*/

ID = [_|a-z|A-Z][a-z|A-Z|0-9_]*
INTEIRO = 0|[1-9][0-9]*
%%

("se")		{return new Symbol(sym.SE, yychar, yyline, yytext());}
("senao")	{return new Symbol(sym.SENAO, yychar, yyline, yytext());}
("senaose")	{return new Symbol(sym.SENAOSE, yychar, yyline, yytext());}
("enquanto")	{return new Symbol(sym.ENQUANTO, yychar, yyline, yytext());}
("faca")	{return new Symbol(sym.FACA, yychar, yyline, yytext());}
("para")	{return new Symbol(sym.PARA, yychar, yyline, yytext());}
("+")		{return new Symbol(sym.MAIS, yychar, yyline, yytext());}
("-")		{return new Symbol(sym.MENOS, yychar, yyline, yytext());}
("*")		{return new Symbol(sym.VEZES, yychar, yyline, yytext());}
("/")		{return new Symbol(sym.DIVISAO, yychar, yyline, yytext());}
("=")		{return new Symbol(sym.IGUAL, yychar, yyline, yytext());}
("<")		{return new Symbol(sym.MENOR, yychar, yyline, yytext());}
(">")		{return new Symbol(sym.MAIOR, yychar, yyline, yytext());}
("<=")          {return new Symbol(sym.MENORIGUAL, yychar, yyline, yytext());}
(">=")		{return new Symbol(sym.MAIORIGUAL, yychar, yyline, yytext());}
(";")		{return new Symbol(sym.PTVIRG, yychar, yyline, yytext());}
("{")           {return new Symbol(sym.ACHAVE, yychar, yyline, yytext());}
("}")           {return new Symbol(sym.FCHAVE, yychar, yyline, yytext());}
("(")           {return new Symbol(sym.APARENT, yychar, yyline, yytext());}
(")")           {return new Symbol(sym.FPARENT, yychar, yyline, yytext());}
{INTEIRO}	{return new Symbol(sym.INTEIRO, yychar, yyline, yytext());}
{ID}		{return new Symbol(sym.ID, yychar, yyline, yytext());}
{BRANCO}	{}
. {System.err.println("Caractere Ilegal: " + yytext());}

```

Error:
```
PS C:\Users\jefh_\OneDrive\Área de Trabalho\Compiladores\Compilador\src\sintatico> jflex scanner.flex
Reading "scanner.flex"
Constructing NFA :
Unexpected exception encountered. This indicates a bug in JFlex.
Please consider filing an issue at http://github.com/jflex-de/jflex/issues/new


Index 31 out of bounds for length 31
java.lang.IndexOutOfBoundsException: Index 31 out of bounds for length 31
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
        at java.base/java.util.Objects.checkIndex(Objects.java:385)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at jflex.core.unicode.CharClasses.getClassCode(CharClasses.java:191)
        at jflex.core.NFA.insertStringNFA(NFA.java:544)
        at jflex.core.NFA.insertNFA(NFA.java:912)
        at jflex.core.NFA.addRegExp(NFA.java:187)
        at jflex.core.LexParse$CUP$LexParse$actions.CUP$LexParse$do_action_part00000000(LexParse.java:1057)
        at jflex.core.LexParse$CUP$LexParse$actions.CUP$LexParse$do_action(LexParse.java:2257)
        at jflex.core.LexParse.do_action(LexParse.java:598)
        at java_cup.runtime.lr_parser.parse(lr_parser.java:699)
        at jflex.generator.LexGenerator.generate(LexGenerator.java:74)
        at jflex.Main.generate(Main.java:320)
        at jflex.Main.main(Main.java:336)
```

**Comment by lsf37** [comment]
A small spec that produces the same exception:

```jflex
%%

%full
%ignorecase

%%

s {}
sn {}
```

**Comment by lsf37** [comment]
And even smaller:

```jflex
%%

%full
%ignorecase

%%

sb {}
```

Looks like one of the ignore-case characters for `s` is not in the char set allowed by `%full`
